version: "3"
services:
  web:
    build:
      context: ./apache-php2
    ports:
      - 80:80
    privileged: true
    links:
      - db
    volumes:
      - "./lara-d-2nd:/var/www/html"
      - "./apache-php2/apache.conf:/etc/httpd/conf/httpd.conf"
    container_name: "apache-php2"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: "mysql5.7_2"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    container_name: "phpmyadmin-la2"


